### ISSUE TITLE
Substitutions bar plot title limited to 5 characters

### ISSUE THREAD

**Issue by kubu4** [EpiDiverse/snp#10]
Substitution plots look like this:

![image](https://user-images.githubusercontent.com/4514104/179624432-220fe1cf-2743-4cd9-a6bf-9183604b45ba.png)

The full samples name is: `zr1394_18_s456_trimmed`.

The character limitation makes it difficult to determine which sample the user is currently viewing (especially when attempting to view multiple plots to compare across an experiment).

**Comment by kubu4** [comment]
I've attempted to resolve this, but I can't seem to get anywhere with it. Found this section in the `plot-vcfstats` script which appears to be where this 5 character limit is established:

```perl
    for my $id (file_ids($opts))
    {
        if ( @{$$opts{dat}{ID}{$id}[0]}>1 ) { next; }   # shared stats of two files
        my $file = $$opts{dat}{ID}{$id}[0][0];
        if ( !exists($file2title{$file}) )  # create short title
        {
            my $bname = $file;
            $bname =~ s{^.*/}{};
            $bname =~ s{\.vcf\.gz$}{}i;
            if ( length($bname) > 5 ) { $bname = substr($bname,0,5); }
            my $i = 0;
            my $title = $bname;
            while ( exists($title2file{$title}) ) { $title = $bname.chr(66+$i); $i++; }
            $file2title{$file} = $title;
            $title2file{$title} = $file;
        }
    }
```

It seems like [L338](https://github.com/samtools/bcftools/blob/435d80bfc8a31fd78298f084a6ffd0143166d5fd/misc/plot-vcfstats#L338) (`if ( length($bname) > 5 ) { $bname = substr($bname,0,5); }`) should be the obvious culprit. However, even when I remove this entire section (starting from ` if ( !exists($file2title{$file}) )  # create short title`), the substitution plots still have titles truncated to 5 characters.

Any other thoughts on how to tackle this?

**Comment by bio15anu** [comment]
Hi, thanks for noticing this detail! I didn't really want to stray from the default options in the plot-vcfstats tool, as people always want to play around with plots and tailor margins, axes, etc. and it's difficult to make something which works for everybody. In each output directory, there is a `plot.py` script for this exact reason which you can use to modify and re-run the plots as you like, and I think this is suitable for most things of this nature.

In this case however I agree that 5 characters is a bit limiting, so I've pushed a commit [64a7348](https://github.com/EpiDiverse/snp/commit/64a73485dc966eabc5cfe79f5d3713f3c0db8a84) which adds the full title to each plot during the pipeline execution. Let me know if this works for you.

**Comment by kubu4** [comment]
Thanks so much! OMG! I made a _very_ similar change that didn't work. I had modified that line to look like this:

`plot-vcfstats -P -p ${sample}  -t ${sample} ${sample}/${vcf}.stats`

Gah! Didn't think the order of the parameters mattered! 

Thanks again!
