### ISSUE TITLE
Docs are private? 

### ISSUE THREAD

**Issue by bsiranosian** [EpiDiverse/snp#3]
Hi, I'd like to test out your software. When I click the link to the installation page in the readme, I'm brought to a gitbook page that says: 

You are not a member of the EpiDiverse organization, or you don't have permissions to access this space.
Want in? Ask a EpiDiverse administrator to grant you access, or log in with another account.

**Comment by bio15anu** [comment]
Hi, thanks for the interest! The links were added a while back when the documentation wasn't publicly available, and we have yet to update them on the Github page. I'll leave this open to remind me to add them which should be very soon, over the next couple of weeks.

In the meantime here is the open link to the landing page: https://epidiverse.gitbook.io/project/-MfxkdBDZggX_vc_sG5l/

**Comment by kubu4** [comment]
Hi! Just checking in to see if there were any plans to follow up on this to make the documentation publicly accessible.

We're trying to use the pipeline and are having some difficulties, but wanted to make sure we weren't screwing something up before posting issues.
